/* MODULE: backend/internalConfig.js VERSION: v5010.9-WIX-NATIVE-EN
 * Emergency restore + Wix Bookings native EN enums. See artifacts/ssot_align.zip for full commented version.
 */
export const STAFF = Object.freeze({
  IDS: Object.freeze([
    "e556070a-6d6a-402e-8422-11133033ea76",
    "07f7344f-e7e4-4c53-854b-47fd82ac8d40",
    "9b905bfd-1a09-485d-9273-a24a20dfe648",
  ]),
  RESOURCE_TO_DISPLAY: Object.freeze({
    "e556070a-6d6a-402e-8422-11133033ea76": "Marian Madrid",
    "07f7344f-e7e4-4c53-854b-47fd82ac8d40": "Andrea",
    "9b905bfd-1a09-485d-9273-a24a20dfe648": "Alba",
  }),
});
export const BUSINESS_COLLECTIONS = Object.freeze({
  ALERTAS_OPERATIVAS: "AlertasOperativas",
  BOOKING_TRANSACTIONS: "BookingTransactions",
  CAJA_ACTUAL: "CajaActual",
  CATEGORIAS_SERVICIO: "CategoriasServicio",
  CITAS_F2: "CitasF2",
  COMPENSACIONES_PENDIENTES: "CompensacionesPendientes",
  COMPLEMENTOS_CATALOGO: "ComplementosCatalogo",
  DATOS_FISCALES: "DatosFiscales",
  HISTORICO_CIERRES_Z: "HistoricoCierresZ",
  LIBRO_ASIENTOS_CONTABLES_DETALLE: "LibroAsientosContablesDetalle",
  INVENTARIO_STOCK_VENTA: "InventarioStockVenta",
  LIBRO_REGISTRO_FACTURAS_EXPEDIDAS: "LibroRegistroFacturasExpedidas",
});
export const OPERATIONAL_COLLECTIONS = Object.freeze({
  AVAILABILITY_DAYS_CACHE: "AvailabilityDaysCache",
  DUAL_SLOT_CACHE: "DualSlotCache",
  MAPA_STAFF: "MapaStaff",
  MOVIMIENTOS_CAJA: "MovimientosCaja",
  MOVIMIENTOS_INVENTARIO: "MovimientosInventario",
  PROCESSED_WEBHOOK_EVENTS: "ProcessedWebhookEvents",
  PROVEEDORES_LISTA: "ProveedoresLista",
  RATE_LIMIT_BLOCKS: "RateLimitBlocks",
  REGISTROS_HORARIOS_STAFF: "RegistrosHorariosStaff",
  SERVICIOS_CATALOGO: "ServiciosCatalogo",
  SLOT_LOCKS: "SlotLocks",
});
export const FORBIDDEN_COLLECTIONS = Object.freeze([
  "AsientosContables", "EventosSistemaFacturacion", "FacturasRecibidas",
  "ConfiguracionFiscal", "LibroRegistroFacturasRecibidas", "PlanCuentasContables",
]);
export const RECORD_TYPE = Object.freeze({ TERCERO: "TERCERO", CONFIG_SISTEMA: "CONFIG_SISTEMA" });
export const RECORDTYPECONFIGSISTEMA = RECORD_TYPE.CONFIG_SISTEMA;
export const LIBRO_ORIGEN_TIPO = Object.freeze({
  ASIENTOCONTABLE: "ASIENTOCONTABLE", EVENTOSISTEMAFACTURACION: "EVENTOSISTEMAFACTURACION",
  MOVIMIENTOCAJA: "MOVIMIENTOCAJA", CIERREZ: "CIERREZ", RECTIFICATIVA: "RECTIFICATIVA",
});
export const LIBRO_ORIGEN_REGISTRO = Object.freeze({
  LIBROASIENTOSCONTABLESDETALLE: "LIBROASIENTOSCONTABLESDETALLE",
  MOVIMIENTOSCAJA: "MOVIMIENTOSCAJA", DATOSFISCALES: "DATOSFISCALES",
});
export const COLLECTIONS = Object.freeze({ ...BUSINESS_COLLECTIONS, ...OPERATIONAL_COLLECTIONS });
export const APP_IDS = Object.freeze({
  BOOKINGS: "13d21c63-b5ec-5912-8397-c3a5ddb27a97",
  STORES: "215238eb-22a5-4c36-9e7b-e7c08025e04e",
  EVENTS: "140603ad-af8d-84fb-9004-ee174e35054d",
  FORMS_PAYMENTS: "14ce1214-b278-a7e4-1373-00cebd1bef7c",
  INVOICES: "13ee94c1-b635-8505-3391-97919052c16f",
  MEMBERS_AREA: "14cc59bc-f0b7-15b8-e1c7-89ce41d0e0c9",
  GIFT_CARDS: "d80111c5-a0f4-47a8-b63a-65b54d774a27",
});
export const API = Object.freeze({
  STAFF_RESOURCE_TYPE_ID: "1cd44cf8-756f-41c3-bd90-3e2ffcaf1155",
  MARIAN_MANAGEMENT_RESOURCE_ID: "e556070a-6d6a-402e-8422-11133033ea76",
});
export const SINGLETONS = Object.freeze({ CAJA: "CAJA_PRINCIPAL" });
export const SDK_CONFIG = Object.freeze({
  TZ: "Europe/Madrid",
  LOCATION_ID: "7a12abfd-bf30-4847-bcdf-00dc573d4802",
  LOCATION_TYPES: Object.freeze({ TIME_SLOTS: "BUSINESS", BOOKINGS_WRITER: "OWNER_BUSINESS" }),
  TIMEOUTS: Object.freeze({
    API_MS: 15000, BOOKING_CREATION_MS: 25000, DUAL_BOOKING_MS: 40000,
    CHECKOUT_MS: 20000, CMS_MS: 15000, WATCHDOG_MS: 30000, WEBHOOK_MS: 30000,
  }),
  CACHE: Object.freeze({
    SERVICES_TTL_MS: 600000, SLOTS_CACHE_TTL_MS: 120000, DUAL_CACHE_TTL_MS: 900000,
    STAFF_TTL_MS: 300000, MAX_ENTRIES: 100, DAYS_CACHE_VERSION: 1, AVAILABILITY_CACHE_TTL_MS: 600000,
  }),
  SECURITY: Object.freeze({ SECRET_CACHE_TTL_MS: 300000, RATE_LIMIT_CACHE_CLEANUP_TTL_MS: 60000, RATE_LIMIT_CACHE_MAX_ENTRIES: 5000 }),
  RATE_LIMIT: Object.freeze({
    MAX_REQUESTS: 20, WINDOW_MS: 5000, BOOKING_MAX_REQUESTS: 5, BOOKING_WINDOW_MS: 10000,
    AVAILABILITY_WINDOW_MS: 5000, AVAILABILITY_REQUESTER_MAX_REQUESTS: 12, AVAILABILITY_GLOBAL_MAX_REQUESTS: 120,
  }),
  JOBS: Object.freeze({
    TIMEOUT_MS: 30000, AUDIT_RETENTION_DAYS: 90, DELETE_BATCH_SIZE: 100, DELETE_MAX_PAGES: 10,
    DUAL_CACHE_CLEANUP_LIMIT: 100, FISCAL_RECOVERY_BATCH_SIZE: 25, HEALTH_CHECK_QUERY_LIMIT: 1000,
    FISCAL_DAILY_MAX_PAGES: 50, BOOKINGS_SERVICE_SYNC_MAX_ATTEMPTS: 5, BOOKINGS_SERVICE_SYNC_BATCH_SIZE: 20,
    BOOKINGS_SERVICE_SYNC_BACKOFF_MS: 300000, M365_GRAPH_SYNC_BATCH_SIZE: 20, M365_GRAPH_SYNC_MAX_ATTEMPTS: 3,
    M365_GRAPH_SYNC_BACKOFF_MS: 300000,
  }),
  EVENTS: Object.freeze({ RETRY_ATTEMPTS: 3, RETRY_BASE_BACKOFF_MS: 1000 }),
  EXTERNAL_HTTP: Object.freeze({
    RATE_LIMIT_MAX_REQUESTS: 20, RATE_LIMIT_WINDOW_MS: 5000, HMAC_MAX_CLOCK_SKEW_SECONDS: 60,
    CORS_ALLOWED_ORIGINS: Object.freeze(["https://www.marianmadrid.es", "https://marianmadrid.es"]),
  }),
  M365: Object.freeze({ ENABLED: false }),
  ACCOUNTING: Object.freeze({ ENABLED: false }),
  SYNC_BOOKINGS_SERVICES_ENABLED: false,
  DOCUMENTS: Object.freeze({ DEFAULT_MANAGER_EMAIL: "gestion@marianmadrid.es", MAX_EMAIL_ATTACHMENT_BYTES: 3145728, MAX_EMAIL_SEND_ATTEMPTS: 3 }),
});
export const CONCURRENCY = Object.freeze({
  MS_TTL_MUTEX: 300000, MS_LATIDO: 15000, TRANSACTION_POLL_BASE_MS: 250, TRANSACTION_MAX_WAIT_MS: 3000,
  LOCK_CLEANUP_GRACE_MS: 60000, MAX_COMPENSATION_RETRIES: 3, MS_TTL_MUTEX_ASIENTO: 45000,
  LOCK_RELEASE_MIN_REMAINING_MS: 15000, DEFAULT_DURATION_MIN: 30,
});
export const BOOKING_STATUS = Object.freeze({
  CREATED: "CREATED", PENDING: "PENDING", CONFIRMED: "CONFIRMED", DECLINED: "DECLINED",
  WAITING_LIST: "WAITING_LIST", UPDATED: "UPDATED", CANCELED: "CANCELED", REFUNDED: "REFUNDED",
});
export const INACTIVE_BOOKING_STATUSES = Object.freeze([
  BOOKING_STATUS.CANCELED, BOOKING_STATUS.DECLINED, "REJECTED", "NOSHOW",
]);
export const PAYMENT_STATUS = Object.freeze({
  UNDEFINED: "UNDEFINED", NOT_PAID: "NOT_PAID", UNPAID: "NOT_PAID",
  PENDING_PAYMENT: "PENDING_PAYMENT", PENDING_LEDGER: "PENDING_LEDGER",
  PAID: "PAID", PARTIALLY_PAID: "PARTIALLY_PAID", REFUNDED: "REFUNDED",
  PARTIALLY_REFUNDED: "PARTIALLY_REFUNDED", EXEMPT: "EXEMPT",
});
export const PAYMENT_METHOD = Object.freeze({
  ONLINE: "ONLINE", OFFLINE: "OFFLINE", MEMBERSHIP: "MEMBERSHIP",
  EFECTIVO: "EFECTIVO", TARJETA: "TARJETA", BIZUM: "BIZUM", TARJETA_REGALO: "TARJETA_REGALO",
});
export const AEAT_PAYMENT_METHOD = Object.freeze({
  CASH: "01", CASH_ON_DELIVERY: "02", CREDIT_CARD: "15", BANK_TRANSFER: "20",
  DIGITAL_WALLET: "28", PAYPAL: "29", SEPA_DIRECT_DEBIT: "30", COUNTER_PAYMENT: "99",
});
export const INVOICE_PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDIENTE", PARTIAL: "PARCIAL", PAID: "PAGADO", OVERPAID: "SOBRAPAGO", CANCELLED: "CANCELADO",
});
export const SLOT_SEARCH = Object.freeze({
  MINUTOS_TOLERANCIA: 5, MINUTOS_MAX_HUECO_DUAL: 120, MAX_POR_RESERVA: 5,
});
export const CATALOG_CONFIG = Object.freeze({
  STATES: Object.freeze({ ACTIVO: "ACTIVO", INACTIVO: "INACTIVO", BORRADOR: "BORRADOR" }),
  ACTIVE_NATIVE_IDS: Object.freeze([]),
});
export const BOOKING_FIELDS = Object.freeze({
  STATUS: "status", PAYMENT_STATUS: "paymentStatus", PAIR_TOKEN: "pairToken",
  SERVICE_ID: "serviceId", RESOURCE_ID: "resourceId", BOOKING_ID: "bookingId",
  DATE_YMD: "dateYmd", META: "meta", CUSTOMER_ID: "customerId",
  START_DATE: "startDate", END_DATE: "endDate", DURATION_MINUTES: "durationMinutes",
});
export const MOVEMENT_TYPE = Object.freeze({
  VENTA_EFECTIVO: "VENTA_EFECTIVO", VENTA_TARJETA: "VENTA_TARJETA", VENTA_BIZUM: "VENTA_BIZUM",
  VENTA_ONLINE: "VENTA_ONLINE", VENTA_PRODUCTO: "VENTA_PRODUCTO", VENTA_PRODUCTO_ONLINE: "VENTA_PRODUCTO_ONLINE",
  VENTA_TARJETA_REGALO: "VENTA_TARJETA_REGALO", CANJE_TARJETA_REGALO: "CANJE_TARJETA_REGALO",
  REEMBOLSO: "REEMBOLSO", DEVOLUCION_SERVICIO: "DEVOLUCION_SERVICIO", DEVOLUCION_PRODUCTO: "DEVOLUCION_PRODUCTO",
  AJUSTE: "AJUSTE", PROPINA: "PROPINA", APORTE: "APORTE", RETIRO: "RETIRO", GASTO: "GASTO",
  PAGO_PROVEEDOR: "PAGO_PROVEEDOR", ANTICIPO: "ANTICIPO", FONDO_INICIAL: "FONDO_INICIAL",
  SERVICIO_PROFESIONAL: "SERVICIO_PROFESIONAL",
});
export const COMPENSATION_KIND = Object.freeze({
  STOCK: "STOCK", PAYMENT: "PAGO", BOOKING: "CITA", INVENTORY: "INVENTARIO", FINANCIAL: "FINANCIERA",
  CANCEL_BOOKING: "CANCEL_BOOKING",
});
export const COMPENSATION_STATUS = Object.freeze({
  PENDING: "PENDIENTE", EXECUTED: "EJECUTADO", FAILED: "FALLIDO", CANCELLED: "CANCELADO", REVERSED: "REVERTIDO",
});
export const CASH_REGISTER_STATUS = Object.freeze({ OPEN: "ABIERTA", CLOSED: "CERRADA" });
export const IVA_RATES = Object.freeze({ GENERAL: 0.21, REDUCIDO: 0.1, SUPERREDUCIDO: 0.04, EXENTO: 0 });
export const BOOKING_TYPE = Object.freeze({
  NORMAL: "NORMAL", DUAL: "DUAL", PACKAGE: "PAQUETE", SUBSCRIPTION: "SUSCRIPCION",
  RESCHEDULE: "REENVIAR", CANCELLED: "CANCELADO", COMPLETED: "COMPLETADO", NO_SHOW: "AUSENTE",
});
export function buildInvoiceNumber(year, month, sequenceNumber) {
  const seq = String(sequenceNumber).padStart(4, "0");
  return `${year}${month}-${seq}`;
}
